### ISSUE TITLE
VSCode recommended extensions references extension that can't be found

### ISSUE THREAD

**Issue by mraichelson** [vueschool/pinia-course-boilerplate#1]
The `johnsoncodehk.volar` extension that's referenced in `/.vscode/extensions.json` brings up this message in VSCode when opening the project there for the first time.

<img width="466" alt="CleanShot 2023-01-05 at 08 36 19@2x" src="https://user-images.githubusercontent.com/70476/210806156-4605b457-a049-42e7-89c0-104b3699ce01.png">

Should this be using the official `Vue.volar` instead? [In the VSCode marketplace here.](https://marketplace.visualstudio.com/items?itemName=Vue.volar)

**Comment by danielkellyio** [comment]
Thanks for pointing this out! Since the course was first created the extension has been moved to the official Vue namespace. 

I've updated it here: https://github.com/vueschool/pinia-course-boilerplate/commit/babd3301145fdbe8ddb1ad64ba1a0e9b06fcd546

Thanks!
