### ISSUE TITLE
boilerplate install

### ISSUE THREAD

**Issue by vifeng** [vueschool/pinia-course-boilerplate#2]
**Error**
img
<img width="1280" alt="Capture d’écran 2023-02-05 à 09 13 56" src="https://user-images.githubusercontent.com/22158753/216808736-f6e863f9-a279-4a56-a9cd-63eeb619f6fd.png">

**step to reproduce the error**
```sh
✗ npm install
  4 vulnerabilities (2 moderate, 1 high, 1 critical)
✗ npm audit fix 
  found 0 vulnerabilities
✗ npm run dev     
  Browserslist: caniuse-lite is outdated. Please run:
    npx browserslist@latest --update-db
    Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
  09:05:54 [vite] ✨ new dependencies optimized: vue/server-renderer
  09:05:54 [vite] ✨ optimized dependencies changed. reloading
✗ npx browserslist@latest --update-db 
✗ npm clean-install
✗ npm run dev
```

**Comment by danielkellyio** [comment]
This was an issue with Vite and the proper version of the Vue plugin for Vite.

It has been fixed here: https://github.com/vueschool/pinia-course-boilerplate/commit/af83b83079db344e05e83804e771b5ddd6695a5b

For more info on the issue see this issue on the Vite repo:
https://github.com/vitejs/vite/issues/6043
